version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:2024.w26
        privileged: true
        container_name: oai-gnb
        environment:
            USE_B2XX: 'yes'
            USE_VOLUMED_CONF: True
            USE_ADDITIONAL_OPTIONS: --sa --continuous-tx --log_config.global_log_options level,nocolor,time,line_num,function
        volumes:
            -  /dev/bus/usb/:/dev/bus/usb/
            - ./conf/gnb.sa.bandn78.fr1.51PRB.usrpb210.conf:/opt/oai-gnb/etc/mounted.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.160
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        driver: bridge
        name: oaiworkshop
        ipam:
            config:
                - subnet: 192.168.70.128/26
        driver_opts:
            com.docker.network.bridge.name: "oaiworkshop"
