version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:2024.w26
        privileged: true
        container_name: oai-gnb
        environment:
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
        networks:
            public_net:
                ipv4_address: 192.168.70.160
        volumes:
            - ./conf/gnb.sa.bandn78.fr1.106PRB.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue:
        image: oaisoftwarealliance/oai-nr-ue:2024.w26
        privileged: true
        container_name: oai-nr-ue
        environment: 
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 001010000000101 -C 3619200000 --rfsimulator.serveraddr 192.168.70.160 --log_config.global_log_options level,nocolor,time
        networks:
            public_net:
                ipv4_address: 192.168.70.150
        volumes:
            - ./conf/ue1.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue2:
        image: oaisoftwarealliance/oai-nr-ue:2024.w26
        privileged: true
        container_name: oai-nr-ue2
        environment: 
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 001010000000102 -C 3619200000 --rfsimulator.serveraddr 192.168.70.160 --log_config.global_log_options level,nocolor,time
        volumes:
            - ./conf/ue2.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.151
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: oaiworkshop
